import '@styles/tailwind.css'
import MainLayout from '@components/layouts/MainLayout'
import { Provider } from 'react-redux'
import { ProviderAuth } from '@hooks/useAuth'
import store from '@context/index'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <ProviderAuth>
        <MainLayout>
          <Component {...pageProps} />
        </MainLayout>
      </ProviderAuth>
    </Provider>
  )
}
